# Generated by Django 4.2.2 on 2023-07-25 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_user_registry_delete_user_registrt'),
    ]

    operations = [
        migrations.CreateModel(
            name='todo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('Descbribe', models.TextField()),
                ('Status', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Todo',
                'managed': False,
            },
        ),
    ]
