# Generated by Django 4.2.2 on 2023-07-27 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0003_todo'),
    ]

    operations = [
        migrations.CreateModel(
            name='custom_token',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Jwt_token', models.CharField(max_length=255)),
                ('Sign_in', models.DateTimeField()),
                ('sign_out', models.DateTimeField()),
            ],
            options={
                'db_table': 'Custom_token',
                'managed': False,
            },
        ),
    ]
